#index:
#    path: /
#    controller: App\Controller\DefaultController::index
api_login_check:
  path: /api/login_check

lists:
  type: rest
  resource: App\Controller\ListController
  prefix: api
  
tasks:
  type: rest
  resource: App\Controller\TaskController
  prefix: api

notes:
  type: rest
  resource: App\Controller\NoteController
  prefix: api